#!/bin/bash
cd /opt/geneos/gateway/resources/jmx

PATH=/usr/bin:$PATH

nohup java -classpath ".:xmlrpc-1.2-b1.jar" -Xms2M -Xmx8M -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=5003 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname="192.168.31.113" QueueSamplerClient3 localhost 7033 &
